In [3]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

## Create and Read

#### 1D array

In [6]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [7]:
type(arr1)

numpy.ndarray

In [8]:
arr1.shape


(5,)

In [9]:
arr1.dtype

dtype('int32')

In [10]:
arr1.ndim

1

In [13]:
arr1.size

5

#### 2D array

In [15]:
arr2 = np.array([[1,2,5], [6,7,4]])
arr2

array([[1, 2, 5],
       [6, 7, 4]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape # (row, col)

(2, 3)

In [18]:
arr2.dtype

dtype('int32')

#### 3D array

In [51]:
arr3 = np.array([[[1,2,5], [6,7,4]] ,[[3,2,1], [0,8,4]]])
arr3

array([[[1, 2, 5],
        [6, 7, 4]],

       [[3, 2, 1],
        [0, 8, 4]]])

In [23]:
arr3.ndim

3

In [26]:
arr3.shape

(2, 2, 3)

### Create random array

In [34]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.51289792, 0.45485396, 0.50913551],
        [0.85572766, 0.69370352, 0.95582834]],

       [[0.70909205, 0.11418161, 0.66388843],
        [0.04733809, 0.31451191, 0.97708298]],

       [[0.53025475, 0.07296839, 0.93048538],
        [0.10043525, 0.88410716, 0.56826348]]])

In [35]:
randomArr.dtype

dtype('float64')

In [38]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
zeroes.ndim

3

In [41]:
full = np.full((3,2,3), 8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [44]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [45]:
arr3

array([[[1, 2, 5],
        [6, 7, 4]],

       [[1, 2, 5],
        [6, 7, 4]]])

In [47]:
arr3[0][0]

array([1, 2, 5])

In [53]:
arr3[0:1]

array([[[1, 2, 5],
        [6, 7, 4]]])

In [52]:
arr3[-1]

array([[3, 2, 1],
       [0, 8, 4]])

In [55]:
arr3[(1,0,1)]

2

In [57]:
a1 = np.random.rand(2 ,3, 2)
a2 = np.random.rand(2, 3, 2)

In [58]:
a1

array([[[0.45908199, 0.01373103],
        [0.86869728, 0.98734767],
        [0.74456608, 0.56751578]],

       [[0.48030717, 0.99141479],
        [0.87286782, 0.19118515],
        [0.07667182, 0.45831193]]])

In [59]:
a2

array([[[0.91231381, 0.26626578],
        [0.7235292 , 0.76659422],
        [0.39090795, 0.98112912]],

       [[0.12528025, 0.33460192],
        [0.71164927, 0.50687174],
        [0.32923567, 0.22131752]]])

In [60]:
np.add(a1,a2)

array([[[1.3713958 , 0.27999681],
        [1.59222648, 1.75394189],
        [1.13547403, 1.5486449 ]],

       [[0.60558741, 1.32601671],
        [1.58451709, 0.69805689],
        [0.4059075 , 0.67962945]]])

In [61]:
np.subtract(a1,a2)

array([[[-0.45323182, -0.25253475],
        [ 0.14516807,  0.22075345],
        [ 0.35365814, -0.41361333]],

       [[ 0.35502692,  0.65681287],
        [ 0.16121855, -0.31568659],
        [-0.25256385,  0.23699441]]])

In [62]:
np.divide(a1,a2)

array([[[0.50320622, 0.05156888],
        [1.20063886, 1.2879665 ],
        [1.90470951, 0.57843129]],

       [[3.83386186, 2.96296806],
        [1.22654214, 0.37718644],
        [0.23287824, 2.07083438]]])

In [64]:
np.multiply(a1, a2)

array([[[0.41882684, 0.0036561 ],
        [0.62852785, 0.75689501],
        [0.2910568 , 0.55680626]],

       [[0.060173  , 0.33172929],
        [0.62117575, 0.09690635],
        [0.0252431 , 0.10143246]]])

#### Statistical oprations

In [65]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,5)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a1)

In [66]:
sqrt

5.0

In [67]:
abs

2

In [68]:
power

32

In [69]:
log

3.2188758248682006

### Update

In [71]:
arr3

array([[[1, 2, 5],
        [6, 7, 4]],

       [[3, 2, 1],
        [0, 8, 4]]])

In [76]:
# arre_reshape = arr3.reshape((2,2,1))

### Delete

In [13]:
arr4 = np.random.rand(3,2,4)
arr4

array([[[0.72967632, 0.63760668, 0.80235971, 0.83618086],
        [0.43680927, 0.00684582, 0.21236219, 0.37605233]],

       [[0.92356304, 0.50032953, 0.68669246, 0.21210725],
        [0.72172622, 0.11346182, 0.08720037, 0.47798094]],

       [[0.46075825, 0.96566736, 0.46932771, 0.56818051],
        [0.3804595 , 0.99154315, 0.16657732, 0.18539626]]])

In [15]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [16]:
arr5

array([[[0.43680927, 0.00684582, 0.21236219, 0.37605233]],

       [[0.72172622, 0.11346182, 0.08720037, 0.47798094]],

       [[0.3804595 , 0.99154315, 0.16657732, 0.18539626]]])

In [19]:
np.save("new_array", arr5)

In [20]:
np.load("new_array.npy")

array([[[0.43680927, 0.00684582, 0.21236219, 0.37605233]],

       [[0.72172622, 0.11346182, 0.08720037, 0.47798094]],

       [[0.3804595 , 0.99154315, 0.16657732, 0.18539626]]])